// Content shared by the page: characters, badges, fictional players
/* characters: slug, card file, mascot, group, PT name, EN name, PT / EN description, vote color */
export const CHARS = [
  ['categoria', 'categoria', 'categoria', 'pos', 'Categoria', 'Pure Class', 'O dono da bola e do campo. Humilha todo mundo com categoria.', 'Owns the ball and the pitch. Humbles everyone with pure class.', '#b8902a'],
  ['matador', 'matador', 'matador', 'pos', 'Matador', 'The Finisher', 'Especialista em finalizar jogadas e balançar as redes.', 'A finishing specialist who lives to ripple the net.', '#1a8a9a'],
  ['paredao', 'paredao', 'paredao', 'pos', 'Paredão', 'The Wall', 'Intransponível na defesa. Fechou o gol nos momentos decisivos.', 'Unbeatable at the back. Shut the goal when it mattered.', '#b3302c'],
  ['garcom', 'garcom', 'garcom', 'pos', 'Garçom', 'The Waiter', 'Enxerga o jogo como poucos. Cria chances e distribui assistências.', 'Sees the game like few do. Creates chances and serves assists.', '#5a3fb0'],
  ['xerife', 'xerife', 'xerife', 'pos', 'Xerife', 'The Sheriff', 'Lidera dentro de campo, organiza o time e assume a responsabilidade.', 'Leads on the pitch, organizes the team and takes responsibility.', '#8a4a26'],
  ['driblador', 'driblador', 'driblador', 'pos', 'Driblador', 'The Dribbler', 'Desmonta a marcação com dribles, velocidade e muita habilidade.', 'Breaks the marking with dribbles, speed and skill.', '#8f969c'],
  ['racudo', 'racudo', 'racudo', 'pos', 'Raçudo', 'The Grinder', 'Se destaca pela entrega, intensidade e vontade de vencer.', 'Stands out for effort, intensity and the will to win.', '#7a6a58'],
  ['gol-mais-bonito', 'gol-mais-bonito', 'gol-mais-bonito', 'pos', 'Gol Mais Bonito', 'Goal of the Night', 'A pintura da noite. Marcou o gol mais bonito da rodada.', 'The masterpiece of the night. Scored the round’s best goal.', '#9a7a3a'],
  ['resenha-forte', 'soresenha', 'resenha-forte', 'soc', 'Só Resenha', 'All Banter', 'Responsável pela animação e pela energia do grupo. E não joga nada!', 'Brings the jokes and the energy to the group. Plays nothing, though!', '#8a2a5a'],
  ['delegado', 'delegado', 'delegado', 'soc', 'Delegado', 'The Chief', 'A bola é dele. O resto do time só acompanha a jogada.', 'The ball is his. The rest of the team just watches.', '#b8705a'],
  ['chorao', 'chorao', 'chorao', 'soc', 'Chorão', 'Crybaby', 'Sempre encontra um motivo pra lamentar uma derrota ou um lance perdido.', 'Always finds a reason to mourn a loss or a missed chance.', '#2a6a7a'],
  ['reclamao', 'reclamao', 'reclamao', 'soc', 'Reclamão', 'The Complainer', 'Questiona decisões, marcações e jogadas com frequência.', 'Questions every call, every foul and every pass.', '#2a3a7a'],
  ['paneleiro', 'paneleiro', 'paneleiro', 'neg', 'Paneleiro', 'Clique Guy', 'Prefere jogar sempre com os mesmos parceiros e amigos.', 'Only ever wants to play with the same friends.', '#3a7a3a'],
  ['firuleiro', 'firuleiro', 'firuleiro', 'soc', 'Firuleiro', 'The Show-off', 'Tenta o drible mais difícil quando o passe simples resolveria.', 'Tries the hardest trick when a simple pass would do.', '#7a7020'],
  ['pregueiro', 'pregueiro', 'pregueiro', 'neg', 'Pregueiro', 'Lazybones', 'Corre pouco e parece estar sempre economizando energia.', 'Barely runs and always seems to be saving energy.', '#6a5a4a'],
  ['cone', 'cone', 'cone', 'neg', 'Cone', 'The Cone', 'Teve pouca participação na partida. A bola bateu e voltou.', 'Barely took part in the game. The ball just bounced off.', '#b8602a'],
  ['bagre', 'bagredanoite', 'bagre', 'neg', 'Bagre da Noite', 'Catfish of the Night', 'A pior atuação da rodada. Errou passes, perdeu gols e sofreu em campo.', 'The worst performance of the round. Missed passes, missed goals, rough night.', '#2a7aa8'],
  ['frangueiro', 'frangueiro', 'frangueiro', 'neg', 'Frangueiro', 'Butterfingers', 'O goleiro que toma um gol bobo, com bola fácil que escapa da mão.', 'The keeper who lets in a soft one that slips through his hands.', '#c8a030'],
  ['bragueiro', 'bragueiro', 'bragueiro', 'neg', 'Bragueiro', 'The Giveaway', 'Entrega a bola pro adversário com um passe errado ou saída desastrosa.', 'Hands the ball to the other team with a bad pass or a disastrous clearance.', '#c87070'],
];

export const BADGES = {
  'primeiro-baba': ['Primeiro Baba', 'First Game', 'Jogou a primeira rodada', 'Played your first round'],
  'mvp': ['MVP', 'MVP', 'Foi o MVP da rodada', 'Round MVP'],
  'em-chamas': ['Em Chamas', 'On Fire', 'Personagem bom em 3 rodadas seguidas', 'A good character three rounds in a row'],
  'veterano': ['Veterano', 'Veteran', '10 rodadas jogadas', 'Ten rounds played'],
  'operario': ['Operário', 'Workhorse', 'Levou Raçudo 5 vezes', 'Voted Grinder five times'],
  'imparavel': ['Imparável', 'Unstoppable', 'Personagem bom em 5 rodadas seguidas', 'A good character five rounds in a row'],
  'rei-absoluto': ['Rei Absoluto', 'Absolute King', '5 MVPs', 'Five MVPs'],
  'casca-grossa': ['Casca Grossa', 'Thick Skin', '25 rodadas jogadas', 'Twenty-five rounds played'],
  'resenha-forte': ['Resenha Forte', 'Banter King', '20 personagens de resenha', 'Twenty banter characters'],
  'virada-de-chave': ['Virada de Chave', 'Turnaround', 'Do Bagre ao craque na rodada seguinte', 'From Catfish to star in the next round'],
  'mais-presente': ['Mais Presente', 'Never Misses', 'Todas as rodadas do mês', 'Every round of the month'],
  'consistente': ['Consistente', 'Consistent', 'Presente e bem votado em 8 rodadas seguidas', 'Present and well voted for eight rounds straight'],
  'invicto': ['Invicto', 'Unbeaten', 'Personagem bom em 10 rodadas seguidas', 'A good character ten rounds in a row'],
  'rei-do-mes': ['Rei do Mês', 'King of the Month', 'Mais MVPs no mês', 'Most MVPs in a month'],
  'racudo-do-mes': ['Raçudo do Mês', 'Grinder of the Month', 'Mais votos de Raçudo no mês', 'Most Grinder votes in a month'],
  'craque-da-galera': ['Craque da Galera', 'Crowd’s Star', '10 MVPs', 'Ten MVPs'],
  'querido-da-galera': ['Querido da Galera', 'Crowd Favorite', '50 personagens bons', 'Fifty good characters'],
  'colecionador': ['Colecionador', 'Collector', 'Desbloqueou 8 conquistas', 'Unlocked eight badges'],
  'hall-da-fama': ['Hall da Fama', 'Hall of Fame', '50 rodadas jogadas', 'Fifty rounds played'],
  'alma-do-grupo': ['Alma do Grupo', 'Soul of the Group', '80% das rodadas por 3 meses', '80% of rounds for three months'],
  'primeira-vitoria': ['Primeira Vitória', 'First Win', 'Primeiro MVP da carreira', 'First MVP of your career'],
  'irregular': ['Irregular', 'Up and Down', 'Alternou MVP e Bagre na mesma semana', 'MVP and Catfish in the same week'],
  'ma-fase': ['Má Fase', 'Bad Run', '3 piores personagens seguidos', 'Three bad characters in a row'],
  'so-perde': ['Só Perde', 'Always Loses', '5 derrotas seguidas', 'Five losses in a row'],
  'jogador-invisivel': ['Jogador Invisível', 'Invisible Player', 'Nenhum voto em 3 rodadas', 'No votes for three rounds'],
  'lanterna': ['Lanterna', 'Bottom Place', 'Último no ranking por um mês', 'Last in the ranking for a month'],
  'trofeu-bagre': ['Troféu Bagre', 'Catfish Trophy', '5 vezes Bagre da Noite', 'Catfish of the Night five times'],
  'craque-historico': ['Craque Histórico', 'All-Time Great', '20 MVPs', 'Twenty MVPs'],
  'lenda': ['Lenda', 'Legend', 'MVP em 10 rodadas', 'MVP in ten rounds'],
  'mestre-da-resenha': ['Mestre da Resenha', 'Banter Master', 'Desbloqueou 16 conquistas', 'Unlocked sixteen badges'],
  'lenda-do-baba': ['Lenda do Baba', 'Legend of the Baba', '100 rodadas, 5 MVPs e 50 personagens bons', '100 rounds, five MVPs and fifty good characters'],
  'completo': ['Completo!', 'Completionist', 'Todas as conquistas', 'Every single badge'],
};

export const PLAYERS = [
  { n: 'Rafa', i: 'RF', c: '#ffd166', ovr: 81 }, { n: 'Caju', i: 'CJ', c: '#ffb547', ovr: 79 },
  { n: 'Léo', i: 'LE', c: '#9fe870', ovr: 79 }, { n: 'Vitão', i: 'VT', c: '#9db7ff', ovr: 78 },
  { n: 'Tiago', i: 'TI', c: '#ff9f8a', ovr: 76 }, { n: 'Marquinhos', i: 'MQ', c: '#f7a6d8', ovr: 75 },
  { n: 'Binho', i: 'BI', c: '#c9a7ff', ovr: 73 }, { n: 'Pedrão', i: 'PD', c: '#7fd3ff', ovr: 71 },
  { n: 'Juninho', i: 'JN', c: '#b8e986', ovr: 70 }, { n: 'Dudu', i: 'DU', c: '#8ef0d0', ovr: 68 },
];
export const av = p => `<span class="av" style="background:${p.c}">${p.i}</span>`;
